### ISSUE TITLE
relies on outdated `typed_struct` dependency

### ISSUE THREAD

**Issue by 03juan** [randycoulman/mix_test_interactive#103]
See https://github.com/ejpcmac/typed_struct/issues/43

**Comment by randycoulman** [comment]
@03juan Thanks for the issue! Is this dependency causing problems for you?

It's only used internally in this library and provides all of the functionality we need for now. There are at least two forks that add features that we don't need here, so I don't currently see a reason to switch to a different library, especially given that there are (at least) two competing alternatives.

I'm going to close this, but if it is actually causing problems for you, please re-open and provide additional details.

Thanks!
