### ISSUE TITLE
[BUG] Tests don't run in mix `test` environment (regression)

### ISSUE THREAD

**Issue by cgrothaus** [randycoulman/mix_test_interactive#121]
Thanks a lot for this helpful little tool. I like it very much.

It seems to me that versions >= `4.0.0` don't switch to the mix `test` environment when running tests.
- `mix test` everything ok ✅
- `mix test.interactive` test failures ❌
- `MIX_ENV=test mix test.interactive` everything ok ✅ (this assumes tweaking `only: :dev` to `only: [:dev, :test]` in `mix.exs`)

With versions up to `3.2.1` I could just call `mix test.interactive` as expected.

**Comment by randycoulman** [comment]
@cgrothaus Thanks for opening this issue and for using this tool!

I definitely made a change in 4.0 where `mix test.interactive` no longer explicitly sets the test environment for you. Everything I read in the docs suggests that doing this is not recommended, so I removed the code that was doing it.

That said, when it runs `mix test` it should automatically run it in the `:test` environment just like `mix test` on its own does. I've tested this in three different applications (using either Elixir 1.16 or 1.17), adding a `dbg(Mix.env())` to a test to verify, and the tests are always running in the `:test` environment.

Here are some things you could look at:
- What version of Elixir are you running?
- Are you running the default `test` Mix task, or are you running a different task that runs `test` under the hood?
- Do you have an alias for `test` in your `mix.exs` file?
- Do you have a `preferred_envs` or `preferred_cli_env` definition that overrides the default behavior?

If none of these apply to you, you might try using [preferred_envs](https://hexdocs.pm/mix/Mix.Project.html#module-cli-configuration) to explicitly run your `test` task in the `:test` environment.

If you're still having issues after that, can you please share more details about your project's configuration and I'll see if I can help get to the bottom of it? Thanks!

**Comment by cgrothaus** [comment]
You are right. My assumptions were wrong, `Mix.env()` is correctly set to the `:test` environment.

I'm on a track, but I can't nail it down yet. Only a few of my tests fail with the new v4 version, and they either use `Bypass` or they have to do with obscure options for setting up a SSL client cert with the Erlang `:ssl` module.

I guess this doesn't help you to see clearer, and I currently don't have the time to dig deeper.

But I found out something interesting. It is about how `mix test.interactive` starts the whole application. With v4, there are differences against the v3 behaviour and also against a plain `mix test`. I'll show you. v4 seems to start the application twice (and the first start is in `:dev` mode), whereas v3 and the plain `mix test` only start it once.

To see this, I equipped `runtime.exs` with a `dbg` of `config_env()`:
```elixir
import Config

case config_env() |> dbg() do
#...
end

# ... rest of the file
```
(Note: the `import Config` and the `case config_env()` were already present in my runtime config, I just added the debug statement).

Now, we can contrast the three different test runs.

### mix test.interactive (3.2.1)

```
$ mix test.interactive

Running tests...
[config/runtime.exs:3: (file)]
config_env() #=> :test

Running ExUnit with seed: 557166, max_cases: 16
...

Tests succeed.
```

### mix test

```
$ mix test
[config/runtime.exs:3: (file)]
config_env() #=> :test


07:58:58.514 [info] Migrations already up
Running ExUnit with seed: 950921, max_cases: 16
...

Tests succeed.
```

### mix test.interactive (4.1.1)

```
$ mix test.interactive
[config/runtime.exs:3: (file)]
config_env() #=> :dev


Running tests...
[config/runtime.exs:3: (file)]
config_env() #=> :test

Running ExUnit with seed: 423617, max_cases: 16
...

Some tests fail.
```

There it is. v4 starts the application twice. Or it reads the runtime config twice. This seems to make a difference regarding my failing tests.

Maybe this already helps you to find a potentially weak spot?

**Comment by randycoulman** [comment]
@cgrothaus I've investigated this a bit and I think I understand what's going on, but not what's causing the problems you're seeing with failing tests.

`mix test.interactive` needs to read your application's config to see if there are any configuration settings for itself. Pre-v4.0, the mix task didn't actually specify that requirement, but I corrected that oversight in v4.0.

So I believe that is why you're now seeing the double loading of your `runtime.exs`, once in `:dev` where `mix test.interactive` runs, and once in `:test` where `mix test` starts your application as part of the test run. `mix test.interactive` is now doing what it should have been doing all along.

What happens if you add `dbg(Mix.env())` to the top of your `Application.start` callback? When I do that, I only see the `:test` environment printed one time as part of the test run. There is a difference between loading an app's config and actually starting the application, and I'm curious to see what's happening in your case.

**Comment by cgrothaus** [comment]
I nailed it down.

Here's a sample project: [sample-project.zip](https://github.com/user-attachments/files/17948640/sample-project.zip).

You can run `mix test` and it succeeds and you can run `mix test.interactive` and it fails the test.

I equipped `config.exs` and `runtime.exs` with `dbg(Mix.env())` statements. Please also note – this is important – that I am using `DotenvParser`.

Head of `runtime.exs`:
```elixir
import Config

dbg(Mix.env())

case config_env() do
  :dev ->
    DotenvParser.load_file(".env.development")

  :test ->
    DotenvParser.load_file(".env.test")

  _ ->
    :noop
end

config :demo, :env_settings,
  env_setting1: System.get_env("ENV_VAR1"),
  env_setting2: System.get_env("ENV_VAR2")
```

`.env.development`:
```
ENV_VAR1=development
ENV_VAR2=development
```

`.env.test`:
```
ENV_VAR1=test
```

Failing test:
```elixir
    test "setting2" do
      assert Application.get_env(:demo, :env_settings)[:env_setting2] == nil
    end
```

Failing test output:
```
$ mix test.interactive test/demo/sample_test.exs:9
[config/config.exs:1: (file)]
Mix.env() #=> :dev

[config/config.exs:39: (file)]
Mix.env() #=> :dev

Generated demo app
[config/runtime.exs:3: (file)]
Mix.env() #=> :dev

[config/runtime.exs:114: (file)]
Mix.env() #=> :dev


Running tests...
[config/config.exs:1: (file)]
Mix.env() #=> :test

[config/test.exs:3: (file)]
Mix.env() #=> :test

[config/test.exs:28: (file)]
Mix.env() #=> :test

[config/config.exs:39: (file)]
Mix.env() #=> :test

[config/runtime.exs:3: (file)]
Mix.env() #=> :test

[config/runtime.exs:114: (file)]
Mix.env() #=> :test

Running ExUnit with seed: 339847, max_cases: 20
Excluding tags: [:test]
Including tags: [location: {"test/demo/sample_test.exs", 9}]



  1) test accessing application settings that depend on env vars setting2 (Demo.SampleTest)
     test/demo/sample_test.exs:9
     Assertion with == failed
     code:  assert Application.get_env(:demo, :env_settings)[:env_setting2] == nil
     left:  "development"
     right: nil
     stacktrace:
       test/demo/sample_test.exs:10: (test)


Finished in 0.01 seconds (0.01s async, 0.00s sync)
2 tests, 1 failure, 1 excluded

Ran all test files matching test/demo/sample_test.exs:9

Watching for file changes...

Usage: ? to show more
```

The key is the following: we have a variable `ENV_VAR2` in the development environment file `.env.development` which is not present in the test environment file `.env.test`. Due to the double loading of `runtime.exs`, `DotenvParser.load_file` is executed once for each environment. Each of the calls does `System.put_env` under the hood. 

As the test environment file sets not value for `ENV_VAR2`, the development value is _never overridden_. And the tests rely on that var being not set.

I don't have an idea yet how we can mitigate this elegantly.

**Comment by randycoulman** [comment]
@cgrothaus Nice detective work!

I think the key consideration is that `mix test.interactive` spawns `mix test` using `System.cmd`, which explicitly passes down the environment from the spawning process to the spawned process. In most cases, I think that's the desired behavior, but it is definitely affecting your use case.

Here are a few possible workarounds for you to try (untested):
- In your `.env.test` file, explicitly include a line: `ENV_VAR2=` to unset that variable in the test environment. I'm not sure if DotenvParser supports that or not.
- Run `mix test.interactive` in the test environment. You'd have to make sure that your dependency specification includes it in the `:test` environment. Then, in your `mix.exs` file, you can configure [preferred_envs](https://hexdocs.pm/mix/1.17.3/Mix.Project.html#module-cli-configuration) to run `mix test.interactive` in the `:test` environment.
- Supply your own test runner module using the [runner](https://github.com/randycoulman/mix_test_interactive#runner-use-a-custom-runner-module) configuration option. Your runner would do mostly what the default runner does, but would handle the environment the way you need it handled for your use case.

**Comment by cgrothaus** [comment]
The `preferred_envs` setting to run`mix test.interactive` in the test environment does the trick 👏 !

Thanks a lot!
