### ISSUE TITLE
mix test.interactive <file> runs all tests

### ISSUE THREAD

**Issue by jfpedroza** [randycoulman/mix_test_interactive#122]
After upgrading to 4.1.0, running `mix test.interactive <file>` runs all tests instead of running only the tests in the file. Only `mix test.interactive -- <file>` works.

I think it's a common use case to start with a file that passing `--` all the time seems unnecessary. The files should be forwarded to `mix test` instead of being ignored. What do you think?

**Comment by randycoulman** [comment]
@jfpedroza Thanks for filing this. That's definitely not how I intended this to work, so it's a bug. Working on a fix now.

**Comment by randycoulman** [comment]
@jfpedroza This is fixed in v4.1.1. Thanks again for reporting it!
