### ISSUE TITLE
immediate response

### ISSUE THREAD

**Issue by andyl** [randycoulman/mix_test_interactive#125]
On a [blog post](https://randycoulman.com/blog/2024/10/16/mix-test-interactive/), Randy expresses a wish for 'immediate response': `Jest works by immediately processing keystrokes, so there is no need to press Enter after specifying a command.  As near as I can tell, Elixir (and, under the hood, Erlang) do not support immediate input mode out of the box (the equivalent of the C getc/getchar functions).`

Looks like there may be a `getch` in OTP 28.

https://github.com/erlang/otp/issues/8037

**Comment by randycoulman** [comment]
Thanks for the pointer! I think I ran across that issue when I was investigating. I'll keep my eyes on it.
